[package]
name = "stdless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "stdless"
path = "main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"